"""add automated accessibility observations

Revision ID: 202608130022
Revises: 202608120021
Create Date: 2026-08-13 01:41:48.362725
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "202608130022"
down_revision: str | None = "202608120021"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

ACCESSIBILITY_JOB_CONSTRAINT = (
    "(scan_id IS NOT NULL AND source_refresh_id IS NULL AND scan_comparison_id IS NULL "
    "AND performance_run_id IS NULL AND accessibility_run_id IS NULL) OR "
    "(scan_id IS NULL AND source_refresh_id IS NOT NULL AND scan_comparison_id IS NULL "
    "AND performance_run_id IS NULL AND accessibility_run_id IS NULL) OR "
    "(scan_id IS NULL AND source_refresh_id IS NULL AND scan_comparison_id IS NOT NULL "
    "AND performance_run_id IS NULL AND accessibility_run_id IS NULL "
    "AND job_type = 'scan_comparison_build') OR "
    "(scan_id IS NULL AND source_refresh_id IS NULL AND scan_comparison_id IS NULL "
    "AND performance_run_id IS NOT NULL AND accessibility_run_id IS NULL "
    "AND job_type = 'performance_run') OR "
    "(scan_id IS NULL AND source_refresh_id IS NULL AND scan_comparison_id IS NULL "
    "AND performance_run_id IS NULL AND accessibility_run_id IS NOT NULL "
    "AND job_type = 'accessibility_run') OR "
    "(scan_id IS NULL AND source_refresh_id IS NULL AND scan_comparison_id IS NULL "
    "AND performance_run_id IS NULL AND accessibility_run_id IS NULL "
    "AND website_property_id IS NOT NULL "
    "AND job_type IN ('category_rule_evaluation', 'structured_content_build'))"
)

PREVIOUS_JOB_CONSTRAINT = (
    "(scan_id IS NOT NULL AND source_refresh_id IS NULL AND scan_comparison_id IS NULL "
    "AND performance_run_id IS NULL) OR "
    "(scan_id IS NULL AND source_refresh_id IS NOT NULL AND scan_comparison_id IS NULL "
    "AND performance_run_id IS NULL) OR "
    "(scan_id IS NULL AND source_refresh_id IS NULL AND scan_comparison_id IS NOT NULL "
    "AND performance_run_id IS NULL AND job_type = 'scan_comparison_build') OR "
    "(scan_id IS NULL AND source_refresh_id IS NULL AND scan_comparison_id IS NULL "
    "AND performance_run_id IS NOT NULL AND job_type = 'performance_run') OR "
    "(scan_id IS NULL AND source_refresh_id IS NULL AND scan_comparison_id IS NULL "
    "AND performance_run_id IS NULL AND website_property_id IS NOT NULL "
    "AND job_type IN ('category_rule_evaluation', 'structured_content_build'))"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accessibility_payload_blobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("compression_type", sa.String(length=32), nullable=False),
        sa.Column("raw_byte_size", sa.Integer(), nullable=False),
        sa.Column("stored_byte_size", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_table(
        "accessibility_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("website_property_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("trigger", sa.String(length=32), nullable=False),
        sa.Column("configuration_json", sa.JSON(), nullable=False),
        sa.Column("target_count", sa.Integer(), nullable=False),
        sa.Column("observation_count", sa.Integer(), nullable=False),
        sa.Column("completed_count", sa.Integer(), nullable=False),
        sa.Column("ready_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("axe_core_version", sa.String(length=32), nullable=False),
        sa.Column("detector_bundle_sha256", sa.String(length=64), nullable=False),
        sa.Column("integration_version", sa.String(length=64), nullable=False),
        sa.Column("normalization_version", sa.String(length=64), nullable=False),
        sa.Column("ruleset_profile", sa.String(length=64), nullable=False),
        sa.Column("ruleset_rule_count", sa.Integer(), nullable=False),
        sa.Column("ruleset_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["website_property_id"], ["website_properties.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_accessibility_runs_site_created",
        "accessibility_runs",
        ["website_property_id", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accessibility_runs_status"), "accessibility_runs", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_accessibility_runs_website_property_id"),
        "accessibility_runs",
        ["website_property_id"],
        unique=False,
    )
    op.create_table(
        "accessibility_observations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("accessibility_run_id", sa.Integer(), nullable=False),
        sa.Column("website_property_id", sa.Integer(), nullable=False),
        sa.Column("web_resource_id", sa.Integer(), nullable=False),
        sa.Column("payload_blob_id", sa.Integer(), nullable=True),
        sa.Column("requested_url", sa.Text(), nullable=False),
        sa.Column("final_url", sa.Text(), nullable=True),
        sa.Column("profile", sa.String(length=32), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("axe_core_version", sa.String(length=32), nullable=False),
        sa.Column("detector_bundle_sha256", sa.String(length=64), nullable=False),
        sa.Column("integration_version", sa.String(length=64), nullable=False),
        sa.Column("normalization_version", sa.String(length=64), nullable=False),
        sa.Column("ruleset_profile", sa.String(length=64), nullable=False),
        sa.Column("ruleset_sha256", sa.String(length=64), nullable=False),
        sa.Column("browser_engine", sa.String(length=32), nullable=False),
        sa.Column("browser_version", sa.String(length=128), nullable=True),
        sa.Column("playwright_version", sa.String(length=32), nullable=True),
        sa.Column("profile_json", sa.JSON(), nullable=False),
        sa.Column("violation_rule_count", sa.Integer(), nullable=False),
        sa.Column("violation_node_count", sa.Integer(), nullable=False),
        sa.Column("incomplete_rule_count", sa.Integer(), nullable=False),
        sa.Column("incomplete_node_count", sa.Integer(), nullable=False),
        sa.Column("pass_rule_count", sa.Integer(), nullable=False),
        sa.Column("inapplicable_rule_count", sa.Integer(), nullable=False),
        sa.Column("normalized_sha256", sa.String(length=64), nullable=True),
        sa.Column("error_type", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["accessibility_run_id"], ["accessibility_runs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["payload_blob_id"], ["accessibility_payload_blobs.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["web_resource_id"], ["web_resources.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["website_property_id"], ["website_properties.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "accessibility_run_id",
            "web_resource_id",
            "profile",
            name="uq_accessibility_observation_logical_request",
        ),
    )
    op.create_index(
        op.f("ix_accessibility_observations_accessibility_run_id"),
        "accessibility_observations",
        ["accessibility_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accessibility_observations_error_type"),
        "accessibility_observations",
        ["error_type"],
        unique=False,
    )
    op.create_index(
        "ix_accessibility_observations_latest",
        "accessibility_observations",
        ["website_property_id", "web_resource_id", "profile", "observed_at", "id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accessibility_observations_normalized_sha256"),
        "accessibility_observations",
        ["normalized_sha256"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accessibility_observations_outcome"),
        "accessibility_observations",
        ["outcome"],
        unique=False,
    )
    op.create_index(
        "ix_accessibility_observations_page_observed",
        "accessibility_observations",
        ["web_resource_id", "observed_at", "id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accessibility_observations_payload_blob_id"),
        "accessibility_observations",
        ["payload_blob_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accessibility_observations_profile"),
        "accessibility_observations",
        ["profile"],
        unique=False,
    )
    op.create_index(
        "ix_accessibility_observations_site_observed",
        "accessibility_observations",
        ["website_property_id", "observed_at", "id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accessibility_observations_web_resource_id"),
        "accessibility_observations",
        ["web_resource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accessibility_observations_website_property_id"),
        "accessibility_observations",
        ["website_property_id"],
        unique=False,
    )
    op.create_table(
        "accessibility_rule_evidence",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("accessibility_observation_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("rule_id", sa.String(length=128), nullable=False),
        sa.Column("result_type", sa.String(length=32), nullable=False),
        sa.Column("impact", sa.String(length=32), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("help", sa.Text(), nullable=False),
        sa.Column("help_url", sa.Text(), nullable=True),
        sa.Column("tags_json", sa.JSON(), nullable=False),
        sa.Column("node_count", sa.Integer(), nullable=False),
        sa.Column("rule_evidence_sha256", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["accessibility_observation_id"], ["accessibility_observations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "accessibility_observation_id",
            "result_type",
            "rule_id",
            name="uq_accessibility_rule_evidence",
        ),
    )
    op.create_index(
        "ix_accessibility_rule_current_aggregation",
        "accessibility_rule_evidence",
        ["rule_id", "result_type", "impact", "accessibility_observation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accessibility_rule_evidence_accessibility_observation_id"),
        "accessibility_rule_evidence",
        ["accessibility_observation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accessibility_rule_evidence_impact"),
        "accessibility_rule_evidence",
        ["impact"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accessibility_rule_evidence_result_type"),
        "accessibility_rule_evidence",
        ["result_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accessibility_rule_evidence_rule_evidence_sha256"),
        "accessibility_rule_evidence",
        ["rule_evidence_sha256"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accessibility_rule_evidence_rule_id"),
        "accessibility_rule_evidence",
        ["rule_id"],
        unique=False,
    )
    op.create_table(
        "accessibility_node_evidence",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("accessibility_rule_evidence_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("impact", sa.String(length=32), nullable=True),
        sa.Column("target_json", sa.JSON(), nullable=False),
        sa.Column("html_snippet", sa.Text(), nullable=False),
        sa.Column("html_original_length", sa.Integer(), nullable=False),
        sa.Column("html_truncated", sa.Boolean(), nullable=False),
        sa.Column("failure_summary", sa.Text(), nullable=False),
        sa.Column("node_evidence_sha256", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["accessibility_rule_evidence_id"],
            ["accessibility_rule_evidence.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "accessibility_rule_evidence_id", "position", name="uq_accessibility_node_position"
        ),
    )
    op.create_index(
        op.f("ix_accessibility_node_evidence_accessibility_rule_evidence_id"),
        "accessibility_node_evidence",
        ["accessibility_rule_evidence_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accessibility_node_evidence_node_evidence_sha256"),
        "accessibility_node_evidence",
        ["node_evidence_sha256"],
        unique=False,
    )
    with op.batch_alter_table("background_jobs") as batch:
        batch.drop_constraint("ck_background_job_one_subject", type_="check")
        batch.add_column(sa.Column("accessibility_run_id", sa.Integer(), nullable=True))
        batch.create_foreign_key(
            "fk_background_jobs_accessibility_run_id",
            "accessibility_runs",
            ["accessibility_run_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch.create_index("ix_background_jobs_accessibility_run_id", ["accessibility_run_id"])
        batch.create_check_constraint("ck_background_job_one_subject", ACCESSIBILITY_JOB_CONSTRAINT)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("background_jobs") as batch:
        batch.drop_constraint("ck_background_job_one_subject", type_="check")
        batch.drop_index("ix_background_jobs_accessibility_run_id")
        batch.drop_constraint("fk_background_jobs_accessibility_run_id", type_="foreignkey")
        batch.drop_column("accessibility_run_id")
        batch.create_check_constraint("ck_background_job_one_subject", PREVIOUS_JOB_CONSTRAINT)
    op.drop_index(
        op.f("ix_accessibility_node_evidence_node_evidence_sha256"),
        table_name="accessibility_node_evidence",
    )
    op.drop_index(
        op.f("ix_accessibility_node_evidence_accessibility_rule_evidence_id"),
        table_name="accessibility_node_evidence",
    )
    op.drop_table("accessibility_node_evidence")
    op.drop_index(
        op.f("ix_accessibility_rule_evidence_rule_id"), table_name="accessibility_rule_evidence"
    )
    op.drop_index(
        op.f("ix_accessibility_rule_evidence_rule_evidence_sha256"),
        table_name="accessibility_rule_evidence",
    )
    op.drop_index(
        op.f("ix_accessibility_rule_evidence_result_type"), table_name="accessibility_rule_evidence"
    )
    op.drop_index(
        op.f("ix_accessibility_rule_evidence_impact"), table_name="accessibility_rule_evidence"
    )
    op.drop_index(
        op.f("ix_accessibility_rule_evidence_accessibility_observation_id"),
        table_name="accessibility_rule_evidence",
    )
    op.drop_index(
        "ix_accessibility_rule_current_aggregation", table_name="accessibility_rule_evidence"
    )
    op.drop_table("accessibility_rule_evidence")
    op.drop_index(
        op.f("ix_accessibility_observations_website_property_id"),
        table_name="accessibility_observations",
    )
    op.drop_index(
        op.f("ix_accessibility_observations_web_resource_id"),
        table_name="accessibility_observations",
    )
    op.drop_index(
        "ix_accessibility_observations_site_observed", table_name="accessibility_observations"
    )
    op.drop_index(
        op.f("ix_accessibility_observations_profile"), table_name="accessibility_observations"
    )
    op.drop_index(
        op.f("ix_accessibility_observations_payload_blob_id"),
        table_name="accessibility_observations",
    )
    op.drop_index(
        "ix_accessibility_observations_page_observed", table_name="accessibility_observations"
    )
    op.drop_index(
        op.f("ix_accessibility_observations_outcome"), table_name="accessibility_observations"
    )
    op.drop_index(
        op.f("ix_accessibility_observations_normalized_sha256"),
        table_name="accessibility_observations",
    )
    op.drop_index("ix_accessibility_observations_latest", table_name="accessibility_observations")
    op.drop_index(
        op.f("ix_accessibility_observations_error_type"), table_name="accessibility_observations"
    )
    op.drop_index(
        op.f("ix_accessibility_observations_accessibility_run_id"),
        table_name="accessibility_observations",
    )
    op.drop_table("accessibility_observations")
    op.drop_index(
        op.f("ix_accessibility_runs_website_property_id"), table_name="accessibility_runs"
    )
    op.drop_index(op.f("ix_accessibility_runs_status"), table_name="accessibility_runs")
    op.drop_index("ix_accessibility_runs_site_created", table_name="accessibility_runs")
    op.drop_table("accessibility_runs")
    op.drop_table("accessibility_payload_blobs")
    # ### end Alembic commands ###
