"""Add page history reuse metadata

Revision ID: 5a2ba8ad44fd
Revises: 202608040008
Create Date: 2026-08-04 22:13:10.787365
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "5a2ba8ad44fd"
down_revision: str | None = "202608040008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "html_parse_artifacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_blob_id", sa.Integer(), nullable=False),
        sa.Column("parser_version", sa.String(length=64), nullable=False),
        sa.Column("parser_config_version", sa.String(length=64), nullable=False),
        sa.Column("resolution_base_url", sa.Text(), nullable=False),
        sa.Column("page_title", sa.Text(), nullable=True),
        sa.Column("html_language", sa.String(length=64), nullable=True),
        sa.Column("meta_description", sa.Text(), nullable=True),
        sa.Column("meta_robots", sa.Text(), nullable=True),
        sa.Column("canonical_url", sa.Text(), nullable=True),
        sa.Column("document_encoding", sa.String(length=64), nullable=True),
        sa.Column("viewport", sa.Text(), nullable=True),
        sa.Column("head_sha256", sa.String(length=64), nullable=False),
        sa.Column("parsed_head_json", sa.JSON(), nullable=False),
        sa.Column("anchor_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["content_blob_id"], ["content_blobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "content_blob_id",
            "parser_version",
            "parser_config_version",
            "resolution_base_url",
            name="uq_html_parse_artifact_identity",
        ),
    )
    op.create_index(
        op.f("ix_html_parse_artifacts_content_blob_id"),
        "html_parse_artifacts",
        ["content_blob_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_html_parse_artifacts_head_sha256"),
        "html_parse_artifacts",
        ["head_sha256"],
        unique=False,
    )
    op.create_table(
        "html_parse_anchors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parse_artifact_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("raw_href", sa.Text(), nullable=True),
        sa.Column("resolved_url", sa.Text(), nullable=True),
        sa.Column("anchor_text", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("aria_label", sa.Text(), nullable=True),
        sa.Column("rel", sa.Text(), nullable=True),
        sa.Column("target", sa.String(length=128), nullable=True),
        sa.Column("dom_path", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parse_artifact_id"], ["html_parse_artifacts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("parse_artifact_id", "position", name="uq_parse_anchor_position"),
    )
    op.create_index(
        op.f("ix_html_parse_anchors_parse_artifact_id"),
        "html_parse_anchors",
        ["parse_artifact_id"],
        unique=False,
    )
    op.create_index(
        "ix_parse_anchor_artifact_position",
        "html_parse_anchors",
        ["parse_artifact_id", "position"],
        unique=False,
    )
    with op.batch_alter_table("resource_snapshots") as batch_op:
        batch_op.add_column(sa.Column("parse_artifact_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("reused_from_snapshot_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("retrieval_method", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("parse_method", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("retrieval_http_status", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("retrieval_response_headers", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("network_bytes_transferred", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("request_variant_fingerprint", sa.String(length=64), nullable=True)
        )
        batch_op.add_column(sa.Column("etag", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("last_modified", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("cache_control", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("vary_header", sa.Text(), nullable=True))
        batch_op.create_foreign_key(
            "fk_resource_snapshots_parse_artifact_id",
            "html_parse_artifacts",
            ["parse_artifact_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            "fk_resource_snapshots_reused_from_snapshot_id",
            "resource_snapshots",
            ["reused_from_snapshot_id"],
            ["id"],
            ondelete="SET NULL",
        )
    op.create_index(
        op.f("ix_resource_snapshots_parse_artifact_id"),
        "resource_snapshots",
        ["parse_artifact_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resource_snapshots_parse_method"),
        "resource_snapshots",
        ["parse_method"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resource_snapshots_request_variant_fingerprint"),
        "resource_snapshots",
        ["request_variant_fingerprint"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resource_snapshots_retrieval_http_status"),
        "resource_snapshots",
        ["retrieval_http_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resource_snapshots_retrieval_method"),
        "resource_snapshots",
        ["retrieval_method"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resource_snapshots_reused_from_snapshot_id"),
        "resource_snapshots",
        ["reused_from_snapshot_id"],
        unique=False,
    )
    op.create_index(
        "ix_snapshot_resource_fetched",
        "resource_snapshots",
        ["resource_id", "fetched_at", "id"],
        unique=False,
    )
    op.add_column(
        "scans",
        sa.Column("conditional_request_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "scans", sa.Column("not_modified_count", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "scans", sa.Column("parse_reuse_count", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "scans", sa.Column("full_parse_count", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "scans",
        sa.Column("network_bytes_transferred", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "scans", sa.Column("reused_content_bytes", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scans", "reused_content_bytes")
    op.drop_column("scans", "network_bytes_transferred")
    op.drop_column("scans", "full_parse_count")
    op.drop_column("scans", "parse_reuse_count")
    op.drop_column("scans", "not_modified_count")
    op.drop_column("scans", "conditional_request_count")
    op.drop_index("ix_snapshot_resource_fetched", table_name="resource_snapshots")
    op.drop_index(
        op.f("ix_resource_snapshots_reused_from_snapshot_id"), table_name="resource_snapshots"
    )
    op.drop_index(op.f("ix_resource_snapshots_retrieval_method"), table_name="resource_snapshots")
    op.drop_index(
        op.f("ix_resource_snapshots_retrieval_http_status"), table_name="resource_snapshots"
    )
    op.drop_index(
        op.f("ix_resource_snapshots_request_variant_fingerprint"),
        table_name="resource_snapshots",
    )
    op.drop_index(op.f("ix_resource_snapshots_parse_method"), table_name="resource_snapshots")
    op.drop_index(op.f("ix_resource_snapshots_parse_artifact_id"), table_name="resource_snapshots")
    with op.batch_alter_table("resource_snapshots") as batch_op:
        batch_op.drop_constraint(
            "fk_resource_snapshots_reused_from_snapshot_id", type_="foreignkey"
        )
        batch_op.drop_constraint("fk_resource_snapshots_parse_artifact_id", type_="foreignkey")
        batch_op.drop_column("vary_header")
        batch_op.drop_column("cache_control")
        batch_op.drop_column("last_modified")
        batch_op.drop_column("etag")
        batch_op.drop_column("request_variant_fingerprint")
        batch_op.drop_column("network_bytes_transferred")
        batch_op.drop_column("retrieval_response_headers")
        batch_op.drop_column("retrieval_http_status")
        batch_op.drop_column("parse_method")
        batch_op.drop_column("retrieval_method")
        batch_op.drop_column("reused_from_snapshot_id")
        batch_op.drop_column("parse_artifact_id")
    op.drop_index("ix_parse_anchor_artifact_position", table_name="html_parse_anchors")
    op.drop_index(op.f("ix_html_parse_anchors_parse_artifact_id"), table_name="html_parse_anchors")
    op.drop_table("html_parse_anchors")
    op.drop_index(op.f("ix_html_parse_artifacts_head_sha256"), table_name="html_parse_artifacts")
    op.drop_index(
        op.f("ix_html_parse_artifacts_content_blob_id"), table_name="html_parse_artifacts"
    )
    op.drop_table("html_parse_artifacts")
    # ### end Alembic commands ###
